# Generated by Django 5.1.5 on 2025-01-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0003_order_quantity_alter_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
